/*
 * @Author: Jiangtao
 * @Date: 2019-11-21 13:20:37
 * @LastEditors: Jiangtao
 * @LastEditTime: 2020-03-24 16:05:01
 */
export enum gameEvents {
    updateProp = 1,
    updatePerExp = 2,
    updateCanGetExp = 3,
    updateRank = 5,
    updateBagItems = 6,
    updateBody = 7,
    updatePet = 8,
    updateDropItem = 9,
    updateNextFloor = 10,
    updateTask = 11,
    updateQA = 12,
    updateSign = 13,
    updateFriendRank = 14,
    updateMail = 15,
    updateNewMail = 16,
    updateSystemInfo = 17,
    updatHideBird = 18,
    updateQAReward = 19,
    showTips = 20,
    updatetransinfo = 21,
    updatedailys = 22,
    updateMailChange = 23,
    updatePlayerLevel = 24,
    updateBagItemChange = 25,
    uppdatePetAD = 26,
    refreshVirtualList = 27,
    updateMasterRelation = 28,
    updateParams = 29,
    updateMasterRelationChange = 30,
    updateGraduateTips = 31,
    updateBuff = 32,
    updateBuffChange = 33,
    updatePlayerOffLineExp = 34,
    updateDaoLvInfo = 35,
    updateTreeAward = 36,
    updateMarryList = 37,
    updateOpenMarry = 38,
    updateWeddingInfo = 39,
    updateWeddingGuests = 40,
    updateHongBao = 41,
    updateResSendGift = 42,
    hidetips = 43,
    updateWeddingRanks = 44,
    updatePlayerFields = 45,
    updateXianJin = 46,
    playTransform = 47,
    updatecomposelevel = 48,
    updateguide = 49,
    showUI = 50,
    linkCMD = 51,
    onshow = 52,
}