/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import btn_zhuan from "./btn_zhuan";
import btn_xiuwei from "./btn_xiuwei";
import btn_farm1 from "./btn_farm1";
import btn_linqi from "./btn_linqi";
import btn_sign from "./btn_sign";
import btn_reward from "./btn_reward";
import btn_help from "./btn_help";
import btn_marray from "./btn_marray";
import btn_rank from "./btn_rank";
import btn_menturm from "./btn_menturm";
import btn_friend from "./btn_friend";
import btn_youjian from "./btn_youjian";
import btn_denglu from "./btn_denglu";
import btn_renwu from "./btn_renwu";
import btn_field from "./btn_field";
import btn_bottom from "./btn_bottom";
import btn_bird from "./btn_bird";
import btn_tupo from "./btn_tupo";
import btn_gm from "./btn_gm";
import com_sex from "./com_sex";

export default class Main extends fgui.GComponent {

	public bg1:fgui.GLoader;
	public bg:fgui.GLoader;
	public role:fgui.GGroup;
	public ps:fgui.GGraph;
	public mc_levelup:fgui.GMovieClip;
	public main_Role:fgui.GButton;
	public xinmo:fgui.GMovieClip;
	public tree_left:fgui.GMovieClip;
	public tree_right:fgui.GMovieClip;
	public apps:fgui.GGroup;
	public btn_zhuan:btn_zhuan;
	public btn_tcdb:btn_xiuwei;
	public bottom_hd1:fgui.GImage;
	public n195:fgui.GImage;
	public n196:fgui.GTextField;
	public com_pet:fgui.GComponent;
	public ProgressBar:fgui.GProgressBar;
	public btn_per_exp:fgui.GTextField;
	public btn_tdjh:btn_farm1;
	public com_fabao:fgui.GComponent;
	public main_zs1:fgui.GImage;
	public main_zs2:fgui.GImage;
	public main_shengzi1:fgui.GImage;
	public main_shengzi2:fgui.GImage;
	public n187:fgui.GImage;
	public n188:fgui.GImage;
	public n189:fgui.GImage;
	public n190:fgui.GImage;
	public shengzi:fgui.GGroup;
	public main_top:fgui.GImage;
	public n3:fgui.GImage;
	public tophead:fgui.GComponent;
	public main_fb:fgui.GImage;
	public icon_lingqi1:fgui.GImage;
	public n201:fgui.GTextField;
	public btn_linqi:btn_linqi;
	public main_fb2:fgui.GImage;
	public n204:fgui.GImage;
	public n205:fgui.GTextField;
	public btn_zuanshi:btn_linqi;
	public main_fb3:fgui.GImage;
	public n208:fgui.GImage;
	public n209:fgui.GTextField;
	public btn_hua:btn_linqi;
	public top:fgui.GGroup;
	public btn_sign:btn_sign;
	public btn_reward:btn_reward;
	public btn_help:btn_help;
	public btn_marray:btn_marray;
	public btn_rank:btn_rank;
	public btn_shitu:btn_menturm;
	public btn_hexiu:btn_friend;
	public btn_youjian:btn_youjian;
	public btn_denglu:btn_denglu;
	public btn_renwu:btn_renwu;
	public btn_yaopu:btn_field;
	public APP:fgui.GGroup;
	public btn_tips:fgui.GButton;
	public namelist:fgui.GList;
	public text_jiewei:fgui.GGroup;
	public main_di:fgui.GImage;
	public flyfire:fgui.GMovieClip;
	public btn_fabao:btn_bottom;
	public btn_gongfa:btn_bottom;
	public btn_pet:btn_bottom;
	public btn_dongfu:btn_bottom;
	public n213:fgui.GTextField;
	public qytime:fgui.GTextField;
	public qyicon:fgui.GImage;
	public qy:fgui.GGroup;
	public bottom:fgui.GGroup;
	public bird:btn_bird;
	public btn_tupo:btn_tupo;
	public btn_gm:btn_gm;
	public com_sex:com_sex;
	public c_time:fgui.GTextField;
	public c_time_ani:fgui.GTextField;
	public ball_target:fgui.GGraph;
	public tupo_bar:fgui.GProgressBar;
	public tupo:fgui.GGroup;
	public white_mask:fgui.GGraph;
	public t0:fgui.Transition;
	public t1:fgui.Transition;

	public static URL:string = "ui://l2fhsbqab8m41";

	public static createInstance():Main {
		return <Main>(fgui.UIPackage.createObject("MainUI","Main"));
	}

	public constructor() {
		super();
	}

	protected onConstruct(): void {
		this.bg1 = <fgui.GLoader>(this.getChildAt(0));
		this.bg = <fgui.GLoader>(this.getChildAt(1));
		this.role = <fgui.GGroup>(this.getChildAt(2));
		this.ps = <fgui.GGraph>(this.getChildAt(3));
		this.mc_levelup = <fgui.GMovieClip>(this.getChildAt(4));
		this.main_Role = <fgui.GButton>(this.getChildAt(5));
		this.xinmo = <fgui.GMovieClip>(this.getChildAt(6));
		this.tree_left = <fgui.GMovieClip>(this.getChildAt(7));
		this.tree_right = <fgui.GMovieClip>(this.getChildAt(8));
		this.apps = <fgui.GGroup>(this.getChildAt(9));
		this.btn_zhuan = <btn_zhuan>(this.getChildAt(10));
		this.btn_tcdb = <btn_xiuwei>(this.getChildAt(11));
		this.bottom_hd1 = <fgui.GImage>(this.getChildAt(12));
		this.n195 = <fgui.GImage>(this.getChildAt(13));
		this.n196 = <fgui.GTextField>(this.getChildAt(14));
		this.com_pet = <fgui.GComponent>(this.getChildAt(15));
		this.ProgressBar = <fgui.GProgressBar>(this.getChildAt(16));
		this.btn_per_exp = <fgui.GTextField>(this.getChildAt(17));
		this.btn_tdjh = <btn_farm1>(this.getChildAt(18));
		this.com_fabao = <fgui.GComponent>(this.getChildAt(19));
		this.main_zs1 = <fgui.GImage>(this.getChildAt(20));
		this.main_zs2 = <fgui.GImage>(this.getChildAt(21));
		this.main_shengzi1 = <fgui.GImage>(this.getChildAt(22));
		this.main_shengzi2 = <fgui.GImage>(this.getChildAt(23));
		this.n187 = <fgui.GImage>(this.getChildAt(24));
		this.n188 = <fgui.GImage>(this.getChildAt(25));
		this.n189 = <fgui.GImage>(this.getChildAt(26));
		this.n190 = <fgui.GImage>(this.getChildAt(27));
		this.shengzi = <fgui.GGroup>(this.getChildAt(28));
		this.main_top = <fgui.GImage>(this.getChildAt(29));
		this.n3 = <fgui.GImage>(this.getChildAt(30));
		this.tophead = <fgui.GComponent>(this.getChildAt(31));
		this.main_fb = <fgui.GImage>(this.getChildAt(32));
		this.icon_lingqi1 = <fgui.GImage>(this.getChildAt(33));
		this.n201 = <fgui.GTextField>(this.getChildAt(34));
		this.btn_linqi = <btn_linqi>(this.getChildAt(35));
		this.main_fb2 = <fgui.GImage>(this.getChildAt(36));
		this.n204 = <fgui.GImage>(this.getChildAt(37));
		this.n205 = <fgui.GTextField>(this.getChildAt(38));
		this.btn_zuanshi = <btn_linqi>(this.getChildAt(39));
		this.main_fb3 = <fgui.GImage>(this.getChildAt(40));
		this.n208 = <fgui.GImage>(this.getChildAt(41));
		this.n209 = <fgui.GTextField>(this.getChildAt(42));
		this.btn_hua = <btn_linqi>(this.getChildAt(43));
		this.top = <fgui.GGroup>(this.getChildAt(44));
		this.btn_sign = <btn_sign>(this.getChildAt(45));
		this.btn_reward = <btn_reward>(this.getChildAt(46));
		this.btn_help = <btn_help>(this.getChildAt(47));
		this.btn_marray = <btn_marray>(this.getChildAt(48));
		this.btn_rank = <btn_rank>(this.getChildAt(49));
		this.btn_shitu = <btn_menturm>(this.getChildAt(50));
		this.btn_hexiu = <btn_friend>(this.getChildAt(51));
		this.btn_youjian = <btn_youjian>(this.getChildAt(52));
		this.btn_denglu = <btn_denglu>(this.getChildAt(53));
		this.btn_renwu = <btn_renwu>(this.getChildAt(54));
		this.btn_yaopu = <btn_field>(this.getChildAt(55));
		this.APP = <fgui.GGroup>(this.getChildAt(56));
		this.btn_tips = <fgui.GButton>(this.getChildAt(57));
		this.namelist = <fgui.GList>(this.getChildAt(58));
		this.text_jiewei = <fgui.GGroup>(this.getChildAt(59));
		this.main_di = <fgui.GImage>(this.getChildAt(60));
		this.flyfire = <fgui.GMovieClip>(this.getChildAt(61));
		this.btn_fabao = <btn_bottom>(this.getChildAt(62));
		this.btn_gongfa = <btn_bottom>(this.getChildAt(63));
		this.btn_pet = <btn_bottom>(this.getChildAt(64));
		this.btn_dongfu = <btn_bottom>(this.getChildAt(65));
		this.n213 = <fgui.GTextField>(this.getChildAt(66));
		this.qytime = <fgui.GTextField>(this.getChildAt(67));
		this.qyicon = <fgui.GImage>(this.getChildAt(68));
		this.qy = <fgui.GGroup>(this.getChildAt(69));
		this.bottom = <fgui.GGroup>(this.getChildAt(70));
		this.bird = <btn_bird>(this.getChildAt(71));
		this.btn_tupo = <btn_tupo>(this.getChildAt(72));
		this.btn_gm = <btn_gm>(this.getChildAt(73));
		this.com_sex = <com_sex>(this.getChildAt(74));
		this.c_time = <fgui.GTextField>(this.getChildAt(75));
		this.c_time_ani = <fgui.GTextField>(this.getChildAt(76));
		this.ball_target = <fgui.GGraph>(this.getChildAt(77));
		this.tupo_bar = <fgui.GProgressBar>(this.getChildAt(78));
		this.tupo = <fgui.GGroup>(this.getChildAt(79));
		this.white_mask = <fgui.GGraph>(this.getChildAt(80));
		this.t0 = this.getTransitionAt(0);
		this.t1 = this.getTransitionAt(1);
	}
}